#!/usr/bin/env bash

set -euo pipefail

set -x
git clean -x -d -f .
./autogen.sh
rm -fr build
mkdir -p build
(
    cd build
    # if [[ -d /opt/homebrew ]]; then
    #     export TREE_SITTER_CFLAGS="-I/opt/homebrew/include/tree_sitter"
    #     export TREE_SITTER_LIBS="-l/opt/homebrew/lib/libtree-sitter.a"
    # fi

    ../configure --with-native-compilation --with-tree-sitter --with-json '--program-transform-name=s/^ctags$/ctags.emacs/' --prefix=$HOME/.local --without-ns --without-x --with-mailutils
    make -j8
    make install
)
