#!/bin/bash

function cmd() {
   echo "$@"
   "$@"
}

(cd home || exit
for a in * ; do
    cmd stow -t ~ "$a"
done)

cmd rm -f ~/.gitignore
cmd ln -s ~/.dotfiles/home/git/.gitignore ~/.gitignore

(cd config || exit
mkdir -p ~/.config
for a in * ; do
    cmd stow -t ~/.config "$a"
done)
