#! /bin/bash

export PATH=/usr/local/bin:"$PATH"

HOST="`hostname`"
case "$HOST" in
    andrewruder-hplin)
        xrandr --output DVI-0 --left-of DVI-1
        ;;
esac

bspc config border_width        2
bspc config window_gap         8

PADDING=10

bspc config top_padding $PADDING
bspc config bottom_padding $PADDING
bspc config left_padding $PADDING
bspc config right_padding $PADDING

#HOLO
bspc config focused_border_color "#33B5E5"
bspc config normal_border_color "#333333"

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

nummons=$(bspc query -M | wc -l)
mon=0
bspc query -M | while read line ; do
    bspc monitor "$line" -d $((0 * nummons + mon)) \
                            $((1 * nummons + mon)) \
                            $((2 * nummons + mon)) \
                            $((3 * nummons + mon)) \
                            $((4 * nummons + mon))
    mon=$((mon+1))
done

bspc rule -a Gimp follow=on floating=on
bspc rule -a Nautilus border=off

feh --bg-fill ~/.wallpaper
setxkbmap -option caps:super -option compose:lwin
sxhkd &
