#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

PADDING=13

bspc config top_padding $PADDING
bspc config bottom_padding $PADDING
bspc config left_padding $PADDING
bspc config right_padding $PADDING

#HOLO
bspc config focused_border_color "#33B5E5"
bspc config normal_border_color "#333333"

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc rule -a Gimp follow=on floating=on
bspc rule -a Nautilus border=off

feh --bg-fill ~/.wallpaper
setxkbmap -option caps:super -option compose:lwin
sxhkd &
