#! /bin/bash

export PATH=/usr/local/bin:"$PATH"

HOST="`hostname`"
case "$HOST" in
    andrewruder-hplin)
        xrandr --output DVI-0 --left-of DVI-1
        ;;
esac

bspc config border_width        4
bspc config window_gap         2

PADDING=0

bspc config top_padding $PADDING
bspc config bottom_padding $PADDING
bspc config left_padding $PADDING
bspc config right_padding $PADDING

#HOLO
bspc config focused_border_color "#ff00ff"
bspc config normal_border_color "#440044"

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

nummons=$(bspc query -M | wc -l)
mon=0
bspc query -M | while read line ; do
    bspc monitor "$line" -d $((0 * nummons + mon)) \
                            $((1 * nummons + mon)) \
                            $((2 * nummons + mon)) \
                            $((3 * nummons + mon)) \
                            $((4 * nummons + mon))
    mon=$((mon+1))
done

bspc rule -a Gimp follow=on floating=on
bspc rule -a Nautilus border=off

xinput --set-prop "CyPS/2 Cypress Trackpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "CyPS/2 Cypress Trackpad" "libinput Tapping Enabled" 1
xinput --set-button-map "Microsoft Microsoft 3-Button Mouse with IntelliEye(TM)" 1 2 3 5 4

setxkbmap -option caps:super -option compose:lwin
start-pulseaudio-x11
feh --bg-fill ~/.wallpaper
sxhkd &
