#! /bin/sh

export PANEL_DIR="`dirname "$0"`"
. "$PANEL_DIR"/config

if [ -e "$PANEL_DIR"/config.local ]; then
    . "$PANEL_DIR"/config.local
fi

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
"$PANEL_DIR"/panel_volume > "$PANEL_FIFO" &
"$PANEL_DIR"/panel_music > "$PANEL_FIFO" &
"$PANEL_DIR"/panel_misc > "$PANEL_FIFO" &
while true ; do date +'S%a %H:%M' ; sleep 3 ; done > "$PANEL_FIFO" &

. "$PANEL_DIR"/panel_colors

"$PANEL_DIR"/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g $PANEL_GEOM -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
