#!/usr/bin/env bash

cpuload() {
    result="`mpstat 2 1 | tail -n 1 | awk '$12 ~ /[0-9.]+/ { print 100 - $12 }'`"
    printf "C%s\n" "$result"
}

memused() {
    read t f <<< `grep -E 'Mem(Total|Available)' /proc/meminfo |awk '{print $2}'`
    result="`bc <<< "scale=2; 100 - $f / $t * 100" | cut -d. -f1`"
    printf "U%s\n" "$result"
}

while true ; do
    cpuload
    memused
    sleep 1.5
done
